repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: mixed-line-ending
    - id: no-commit-to-branch
      args: [--branch, master, --branch, develop]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      args: [--profile, black]

- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
    - id: black
      args: [--line-length=120]

- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8-docstrings
      args: [--config, setup.cfg]
