services:
  backend:
    image: ghcr.io/studio-yandex-practicum/procharity_back_2.0:stage
    container_name: procharity_bot_backend
    restart: always
    volumes:
      - ./logs/:/app/logs/
    depends_on:
        postgres:
          condition: service_healthy
    ports:
        - "8000:8000"
    env_file:
        - ../.env
    command: ./infra/entrypoints/staging.sh

  postgres:
    image: postgres:13.2
    container_name: procharity_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "{{ POSTGRES_USER | 'postgres' }}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.23.3-alpine
    container_name: procharity_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ../.env

volumes:
  postgres_data:
