SUBCATEGORIES = r"category_(\d+)"
SELECT_CATEGORY = r"select_category_(\d+)"
BACK_SUBCATEGORY = r"back_to_(\d+)"
NO_MAILING_REASON = r"reason_(\w+)"
RESPOND_TO_TASK = r"([+-])respond_to_task_(\d+)"
CANCEL_RESPOND_REASON = r"cancel_respond_to_task_(\d+)_reason_(\w+)"
KEEP_TASK_RESPOND = r"keep_respond_to_task_(\d+)"
NOTIFICATION_FIELD_CALLBACK = r"notification_(\w+)_callback"
