"""Notification sent_by set nullable

Revision ID: 0e74b21e97f4
Revises: 87c7d29e3ddb
Create Date: 2023-07-03 17:44:30.800774

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e74b21e97f4"
down_revision = "87c7d29e3ddb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("notifications", "sent_by", existing_type=sa.VARCHAR(length=48), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("notifications", "sent_by", existing_type=sa.VARCHAR(length=48), nullable=False)
    # ### end Alembic commands ###
