"""add_admin_user_model

Revision ID: 9ce2090b58a9
Revises: 42469a350651
Create Date: 2023-08-13 15:31:22.429548

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9ce2090b58a9"
down_revision = "42469a350651"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_token_requests",
        sa.Column("email", sa.String(length=48), nullable=False),
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column("token_expiration_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "admin_users",
        sa.Column("email", sa.String(length=48), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("last_logon", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.alter_column("external_site_users", "specializations", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("external_site_users", "specializations", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_table("admin_users")
    op.drop_table("admin_token_requests")
    # ### end Alembic commands ###
