"""feature_models

Revision ID: 36bbdf5f665b
Revises: cf3d7f01689e
Create Date: 2023-05-21 16:29:17.282821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bbdf5f665b'
down_revision = 'cf3d7f01689e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
