"""add users_categories model

Revision ID: 84e25a1e5eee
Revises: edf9d4b6cdea
Create Date: 2023-05-30 13:47:15.877246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e25a1e5eee'
down_revision = 'edf9d4b6cdea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_categories', sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('users_categories', sa.Column('updated_at', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_constraint('users_categories_category_id_key', 'users_categories', type_='unique')
    op.drop_constraint('users_categories_user_id_key', 'users_categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_categories_user_id_key', 'users_categories', ['user_id'])
    op.create_unique_constraint('users_categories_category_id_key', 'users_categories', ['category_id'])
    op.drop_column('users_categories', 'updated_at')
    op.drop_column('users_categories', 'created_at')
    # ### end Alembic commands ###
