"""fix_task_and_category_ models_fields

Revision ID: cf3d7f01689e
Revises: ff7829853115
Create Date: 2023-05-21 01:06:16.399380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3d7f01689e'
down_revision = 'ff7829853115'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('name_organization', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('deadline', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('tasks', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'deadline')
    op.drop_column('tasks', 'name_organization')
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
