"""add unique_user_category constraint

Revision ID: 44c2f42e877d
Revises: edf9d4b6cdea
Create Date: 2023-05-27 13:29:14.223290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c2f42e877d'
down_revision = 'edf9d4b6cdea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_categories_category_id_key', 'users_categories', type_='unique')
    op.drop_constraint('users_categories_user_id_key', 'users_categories', type_='unique')
    op.create_unique_constraint('unique_user_category', 'users_categories', ['category_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_category', 'users_categories', type_='unique')
    op.create_unique_constraint('users_categories_user_id_key', 'users_categories', ['user_id'])
    op.create_unique_constraint('users_categories_category_id_key', 'users_categories', ['category_id'])
    # ### end Alembic commands ###
