"""feature_category_ model

Revision ID: 43c039ce0388
Revises: cf3d7f01689e
Create Date: 2023-05-21 02:32:21.948094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c039ce0388'
down_revision = 'cf3d7f01689e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
