"""add users_categories model

Revision ID: ff506e4aff3b
Revises: edf9d4b6cdea
Create Date: 2023-05-27 18:47:11.909190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff506e4aff3b'
down_revision = 'edf9d4b6cdea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint('users_categories_category_id_key', 'users_categories', type_='unique')
    op.drop_constraint('users_categories_user_id_key', 'users_categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_categories_user_id_key', 'users_categories', ['user_id'])
    op.create_unique_constraint('users_categories_category_id_key', 'users_categories', ['category_id'])
    op.drop_column('users', 'is_archived')
    # ### end Alembic commands ###
