"""feature_category_and_task_model

Revision ID: bfcd4000571b
Revises: cf3d7f01689e
Create Date: 2023-05-21 12:41:59.602046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcd4000571b'
down_revision = 'cf3d7f01689e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
