"""fixture models

Revision ID: 009a63000786
Revises: bb02384217e4
Create Date: 2023-05-21 19:24:23.804527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009a63000786'
down_revision = 'bb02384217e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.drop_column('categories', 'archive')
    op.add_column('tasks', sa.Column('title', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('name_organization', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('deadline', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.drop_column('tasks', 'archive')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('archive', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'is_archived')
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'deadline')
    op.drop_column('tasks', 'name_organization')
    op.drop_column('tasks', 'title')
    op.add_column('categories', sa.Column('archive', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'is_archived')
    # ### end Alembic commands ###
