"""add users_categories model

Revision ID: dc92b818969c
Revises: edf9d4b6cdea
Create Date: 2023-05-28 00:04:23.403075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc92b818969c'
down_revision = 'edf9d4b6cdea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_categories_category_id_key', 'users_categories', type_='unique')
    op.drop_constraint('users_categories_user_id_key', 'users_categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_categories_user_id_key', 'users_categories', ['user_id'])
    op.create_unique_constraint('users_categories_category_id_key', 'users_categories', ['category_id'])
    # ### end Alembic commands ###
