"""empty message

Revision ID: b7b57ebbbd25
Revises: b5085c436c0d
Create Date: 2023-04-17 19:53:52.211124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b57ebbbd25'
down_revision = 'b5085c436c0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'user_id'),
    sa.UniqueConstraint('category_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_table('users_categories')
    # ### end Alembic commands ###
