"""add_unsubscribe_reason

Revision ID: 6c4739908b74
Revises: f73ffa2605e1
Create Date: 2023-09-19 20:59:01.601531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4739908b74'
down_revision = 'f73ffa2605e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unsubscribe_reason',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unsubscribe_reason', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unsubscribe_reason')
    # ### end Alembic commands ###
