"""add_unsubscribe_reason

Revision ID: 3178127e32e7
Revises: f73ffa2605e1
Create Date: 2023-09-09 14:47:01.310977

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3178127e32e7'
down_revision = 'f73ffa2605e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unsubscribe_reason',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('unsubscribe_reason', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unsubscribe_reason')
    # ### end Alembic commands ###
