"""add column created_at and updated_at

Revision ID: bb02384217e4
Revises: 343ddd1cf565
Create Date: 2023-05-10 16:34:51.135677

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bb02384217e4"
down_revision = "343ddd1cf565"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories", sa.Column("created_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False)
    )
    op.add_column(
        "categories", sa.Column("updated_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False)
    )
    op.add_column("tasks", sa.Column("bonus", sa.Integer(), nullable=False))
    op.add_column("tasks", sa.Column("location", sa.String(), nullable=False))
    op.add_column("tasks", sa.Column("link", sa.String(), nullable=False))
    op.add_column("tasks", sa.Column("archive", sa.Boolean(), nullable=False))
    op.add_column(
        "tasks", sa.Column("created_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False)
    )
    op.add_column(
        "tasks", sa.Column("updated_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False)
    )
    op.drop_column("tasks", "created_date")
    op.drop_column("tasks", "updated_date")
    op.add_column(
        "users", sa.Column("created_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False)
    )
    op.add_column(
        "users", sa.Column("updated_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False)
    )
    op.drop_column("users", "date_registration")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "date_registration",
            sa.DATE(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.add_column(
        "tasks",
        sa.Column(
            "updated_date", sa.DATE(), server_default=sa.text("CURRENT_TIMESTAMP"), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "created_date", sa.DATE(), server_default=sa.text("CURRENT_TIMESTAMP"), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("tasks", "updated_at")
    op.drop_column("tasks", "created_at")
    op.drop_column("tasks", "archive")
    op.drop_column("tasks", "link")
    op.drop_column("tasks", "location")
    op.drop_column("tasks", "bonus")
    op.drop_column("categories", "updated_at")
    op.drop_column("categories", "created_at")
    # ### end Alembic commands ###
