"""feature_category_and_task_model

Revision ID: 0b73358c5202
Revises: cf3d7f01689e
Create Date: 2023-05-21 02:40:48.736530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b73358c5202'
down_revision = 'cf3d7f01689e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tasks', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('categories', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
