"""fix_admin_user_model

Revision ID: f73ffa2605e1
Revises: 9ce2090b58a9
Create Date: 2023-08-27 16:19:33.393165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73ffa2605e1'
down_revision = '9ce2090b58a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('last_login', sa.Date(), nullable=True))
    op.drop_column('admin_users', 'last_logon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('last_logon', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('admin_users', 'last_login')
    # ### end Alembic commands ###
