"""add description fields into Task

Revision ID: 01031c0ab38e
Revises: 03ea379fb5c9
Create Date: 2024-06-09 17:13:28.095414

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "01031c0ab38e"
down_revision = "03ea379fb5c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("description_main", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("tasks", sa.Column("description_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("tasks", sa.Column("description_files", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("tasks", sa.Column("description_bonus", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "description_bonus")
    op.drop_column("tasks", "description_files")
    op.drop_column("tasks", "description_links")
    op.drop_column("tasks", "description_main")
    # ### end Alembic commands ###
