"""Add role column to user

Revision ID: d7c8c0e22854
Revises: 02fda211f87e
Create Date: 2024-04-04 21:12:04.315042

"""
import sqlalchemy as sa
from alembic import op

from src.core.enums import UserRoles

# revision identifiers, used by Alembic.
revision = "d7c8c0e22854"
down_revision = "02fda211f87e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "external_site_users",
        sa.Column("role", sa.String(length=20), nullable=False, server_default=UserRoles.VOLUNTEER),
    )
    op.add_column("users", sa.Column("role", sa.String(length=20), nullable=False, server_default=UserRoles.VOLUNTEER))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.drop_column("external_site_users", "role")
    # ### end Alembic commands ###
