"""add field is_archived to external_site_users

Revision ID: e7ac78853018
Revises: 6eb0ef45ad86
Create Date: 2024-05-24 20:54:50.250707

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e7ac78853018"
down_revision = "6eb0ef45ad86"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "external_site_users", sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("external_site_users", "is_archived")
    # ### end Alembic commands ###
