"""fund sections

Revision ID: 061099e77972
Revises: ff5edcfa36a8
Create Date: 2024-02-14 19:30:33.442998

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "061099e77972"
down_revision = "ff5edcfa36a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "fund_sections", existing_type=postgresql.ARRAY(sa.BIGINT()), type_=sa.String(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "fund_sections", existing_type=sa.String(), type_=postgresql.ARRAY(sa.BIGINT()), existing_nullable=True
    )
    # ### end Alembic commands ###
