"""Updated tasks

Revision ID: ff5edcfa36a8
Revises: 76fc39423eba
Create Date: 2024-02-14 18:18:52.179232

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ff5edcfa36a8"
down_revision = "76fc39423eba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("legal_address", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("fund_city", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("fund_rating", sa.Float(), nullable=True))
    op.add_column("tasks", sa.Column("fund_site", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("yb_link", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("vk_link", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("fund_sections", sa.ARRAY(sa.BigInteger()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "fund_sections")
    op.drop_column("tasks", "vk_link")
    op.drop_column("tasks", "yb_link")
    op.drop_column("tasks", "fund_site")
    op.drop_column("tasks", "fund_rating")
    op.drop_column("tasks", "fund_city")
    op.drop_column("tasks", "legal_address")
    # ### end Alembic commands ###
