"""task.description nullable

Revision ID: 54c666ae68f1
Revises: 01031c0ab38e
Create Date: 2024-06-12 00:21:40.135456

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "54c666ae68f1"
down_revision = "01031c0ab38e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "description", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "description", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
