"""add_bot_message_model

Revision ID: 80fd805e8431
Revises: a58802257c7e
Create Date: 2024-07-27 13:01:39.862059

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "80fd805e8431"
down_revision = "a58802257c7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_message",
        sa.Column("text", sa.String(length=4096), nullable=False),
        sa.Column("was_read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bot_message")
    # ### end Alembic commands ###
