"""change_external_site_user

Revision ID: 06992bde18f9
Revises: 52a187f6b04d
Create Date: 2024-02-03 05:39:16.592278

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "06992bde18f9"
down_revision = "52a187f6b04d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("external_site_users", sa.Column("external_id", sa.Integer(), nullable=True))
    op.alter_column("external_site_users", "email", existing_type=sa.VARCHAR(length=48), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("external_site_users", "email", existing_type=sa.VARCHAR(length=48), nullable=False)
    op.drop_column("external_site_users", "external_id")
    # ### end Alembic commands ###
