"""lost_migration

Revision ID: 52a187f6b04d
Revises: 40dc5f0d5736
Create Date: 2024-02-03 05:36:40.239281

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "52a187f6b04d"
down_revision = "40dc5f0d5736"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "external_site_users", ["email"])
    op.alter_column("unsubscribe_reason", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("users_categories", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users_categories", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("unsubscribe_reason", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(None, "external_site_users", type_="unique")
    # ### end Alembic commands ###
