"""add_field_is_superuser_to_admin_token

Revision ID: c47841afb855
Revises: 03553b3c5019
Create Date: 2024-06-03 12:33:57.254531

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c47841afb855"
down_revision = "03553b3c5019"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin_token_requests", sa.Column("is_superuser", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admin_token_requests", "is_superuser")
    # ### end Alembic commands ###
