"""change external site user

Revision ID: 76fc39423eba
Revises: d4e4699c3473
Create Date: 2024-02-13 19:12:46.280347

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "76fc39423eba"
down_revision = "d4e4699c3473"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("external_site_users", sa.Column("external_id", sa.Integer(), nullable=True))
    op.alter_column("external_site_users", "email", existing_type=sa.VARCHAR(length=48), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("external_site_users", "email", existing_type=sa.VARCHAR(length=48), nullable=False)
    op.drop_column("external_site_users", "external_id")
    # ### end Alembic commands ###
