"""add fund_link field to task

Revision ID: 6eb0ef45ad86
Revises: 8e0bf7deadaf
Create Date: 2024-04-27 22:28:51.531910

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6eb0ef45ad86"
down_revision = "8e0bf7deadaf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("fund_link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "fund_link")
    # ### end Alembic commands ###
