"""Added relationship external user

Revision ID: 2e82b00cfd5a
Revises: b053e192b0ec
Create Date: 2024-01-11 16:59:46.087330

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e82b00cfd5a"
down_revision = "b053e192b0ec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("external_site_users", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key("fk_external_site_users_user_id", "external_site_users", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_external_site_users_user_id", "external_site_users", type_="foreignkey")
    op.drop_column("external_site_users", "user_id")
    # ### end Alembic commands ###
