"""drop notifications fields

Revision ID: 797114cc8d65
Revises: 837378a2a99e
Create Date: 2024-08-24 17:48:49.721606

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "797114cc8d65"
down_revision = "837378a2a99e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("external_site_users", "has_mailing_my_tasks")
    op.drop_column("external_site_users", "has_mailing_new_tasks")
    op.drop_column("external_site_users", "has_mailing_procharity")
    op.drop_column("external_site_users", "has_mailing_profile")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "external_site_users", sa.Column("has_mailing_profile", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "external_site_users", sa.Column("has_mailing_procharity", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "external_site_users", sa.Column("has_mailing_new_tasks", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "external_site_users", sa.Column("has_mailing_my_tasks", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
