"""Change type of token_expiration_date

Revision ID: 40dc5f0d5736
Revises: fe9ed9252c2b
Create Date: 2024-01-14 08:10:42.956929

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "40dc5f0d5736"
down_revision = "fe9ed9252c2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admin_token_requests",
        "token_expiration_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.drop_constraint("admin_token_requests_email_key", "admin_token_requests", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("admin_token_requests_email_key", "admin_token_requests", ["email"])
    op.alter_column(
        "admin_token_requests",
        "token_expiration_date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
