"""add is_archived field to ext_site_user

Revision ID: a58802257c7e
Revises: 54c666ae68f1
Create Date: 2024-06-17 21:34:24.170666

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a58802257c7e"
down_revision = "54c666ae68f1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "external_site_users", sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("external_site_users", "is_archived")
    # ### end Alembic commands ###
