"""add role column to user

Revision ID: 8e0bf7deadaf
Revises: 02fda211f87e
Create Date: 2024-04-06 11:18:27.768759

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8e0bf7deadaf"
down_revision = "02fda211f87e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("external_site_users", sa.Column("role", sa.String(length=20), nullable=True))
    op.add_column("users", sa.Column("role", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.drop_column("external_site_users", "role")
    # ### end Alembic commands ###
