"""add_field_moderation_status

Revision ID: 03ea379fb5c9
Revises: c47841afb855
Create Date: 2024-06-05 15:13:19.806169

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "03ea379fb5c9"
down_revision = "c47841afb855"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("external_site_users", sa.Column("moderation_status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("external_site_users", "moderation_status")
    # ### end Alembic commands ###
