"""Group send message - user_id

Revision ID: 26d99cc7348e
Revises: fe9ed9252c2b
Create Date: 2024-01-21 00:24:57.385973

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "26d99cc7348e"
down_revision = "fe9ed9252c2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("external_site_users", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key("fk_external_site_users_user_id", "external_site_users", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_external_site_users_user_id", "external_site_users", type_="foreignkey")
    op.drop_column("external_site_users", "user_id")
    # ### end Alembic commands ###
