"""add_field_is_superuser_to_admin_token_request

Revision ID: 79fb76c49449
Revises: 6eb0ef45ad86
Create Date: 2024-05-30 13:45:31.967934

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "79fb76c49449"
down_revision = "6eb0ef45ad86"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin_token_requests", sa.Column("is_superuser", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admin_token_requests", "is_superuser")
    # ### end Alembic commands ###
