"""empty message

Revision ID: 22b4a7bbaa8b
Revises: fe9ed9252c2b
Create Date: 2024-01-31 08:28:16.301057

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "22b4a7bbaa8b"
down_revision = "fe9ed9252c2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "funds_categories",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("fund_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_at", sa.Date(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fund_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("category_id", "fund_id"),
    )
    # op.drop_constraint('admin_token_requests_email_key', 'admin_token_requests', type_='unique')
    # op.create_unique_constraint(None, 'external_site_users', ['email'])
    op.add_column("tasks", sa.Column("legal_address", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("fund_city", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("fund_rating", sa.Float(), nullable=True))
    op.add_column("tasks", sa.Column("fund_site", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("yb_link", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("vk_link", sa.String(), nullable=True))
    # op.alter_column('unsubscribe_reason', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.drop_constraint('users_id_key', 'users', type_='unique')
    # op.alter_column('users_categories', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users_categories", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # op.create_unique_constraint('users_id_key', 'users', ['id'])
    # op.alter_column('unsubscribe_reason', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    op.drop_column("tasks", "vk_link")
    op.drop_column("tasks", "yb_link")
    op.drop_column("tasks", "fund_site")
    op.drop_column("tasks", "fund_rating")
    op.drop_column("tasks", "fund_city")
    op.drop_column("tasks", "legal_address")
    # op.drop_constraint(None, 'external_site_users', type_='unique')
    # op.create_unique_constraint('admin_token_requests_email_key', 'admin_token_requests', ['email'])
    op.drop_table("funds_categories")
    # ### end Alembic commands ###
