"""Add parrent_id to Categories

Revision ID: 52647dd43d55
Revises: a31c9678bad6
Create Date: 2022-09-10 12:29:00.588351

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "52647dd43d55"
down_revision = "a31c9678bad6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "categories", "categories", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("categories_parent_id_fkey", "categories", type_="foreignkey")
    op.drop_column("categories", "parent_id")
    # ### end Alembic commands ###
