"""change_telegram_id_type

Revision ID: a31c9678bad6
Revises: 65ee3e678174
Create Date: 2022-04-19 19:42:05.846605

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a31c9678bad6"
down_revision = "65ee3e678174"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reasons_canceling", "telegram_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True
    )
    op.alter_column(
        "statistics", "telegram_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True
    )
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('users_telegram_id_seq'::regclass)"),
    )
    op.alter_column(
        "users_categories", "telegram_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users_categories", "telegram_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False
    )
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('users_telegram_id_seq'::regclass)"),
    )
    op.alter_column(
        "statistics", "telegram_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True
    )
    op.alter_column(
        "reasons_canceling", "telegram_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True
    )
    # ### end Alembic commands ###
