name: Stage Deploy

concurrency:
  group: stage_deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: deploy
      label: stage
    secrets: inherit
